module.exports = [
    { slug: 'Chinese' },
    { slug: 'American-Style' },
    { slug: 'Indian' },
    { slug: 'Italian' },
    { slug: 'Japanese' },
    { slug: 'Mexican' },
    { slug: 'Mediterranean' },
    { slug: 'French' },
    { slug: 'Thai' },
    { slug: 'Greek' },
    { slug: 'Spanish' },
    { slug: 'Middle Eastern' },
    { slug: 'Korean' },
    { slug: 'Vietnamese' },
    { slug: 'Brazilian' },
    {slug: 'Vegetarian'},
    {slug: 'Seafood'},
  ];